import type { AgentTemplatePayload, AgentTemplateStatus } from "@first-tree/shared";
import { sql } from "drizzle-orm";
import { type AnyPgColumn, check, index, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

/**
 * Global official Agent Template catalog. Not org-scoped: a Template is a
 * First Tree curated object, never a customer Team Resource.
 *
 * A Template is a one-shot starting configuration: on adoption its payload
 * components are imported into the adopting Team's Resources (which keep
 * `origin_template_id` / `origin_component_key` provenance). This table
 * deliberately stores no customer Resource ids, and Team Resources hold no
 * FK back to this table — Template lifecycle must never affect Team-owned
 * Resources. V1 has no revisioning: updates edit this row in place and only
 * affect Teams that import afterwards.
 *
 * Ids are UUIDv7 text generated by the service layer (same convention as
 * `resources.id`).
 */
export const agentTemplates = pgTable(
  "agent_templates",
  {
    id: text("id").primaryKey(),
    /** Globally unique, immutable once published; used by public URLs. */
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    status: text("status").$type<AgentTemplateStatus>().notNull().default("draft"),
    payload: jsonb("payload").$type<AgentTemplatePayload>().notNull(),
    /** Optional successor suggested when this Template is retired. */
    replacementTemplateId: text("replacement_template_id").references((): AnyPgColumn => agentTemplates.id, {
      onDelete: "set null",
    }),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("uq_agent_templates_slug").on(table.slug),
    index("idx_agent_templates_status").on(table.status),
    check("ck_agent_templates_status", sql`${table.status} IN ('draft', 'active', 'retired')`),
  ],
);
